[project]
name = "mygeopy"
version = "0.0.1"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project.optional-dependencies]
tests = ["pytest"]

[tool.pytest.ini_options]
addopts = "--doctest-modules"