[project]
name = "mygeopy"
project.version = "0.0.1"
description = "Testing tests"

dependencies = [
    "numpy",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"